<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Sandisk</name>
   <tag></tag>
   <elementGuidId>0c802be7-f415-4a5d-999e-013a3bb1d496</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wrapword</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sandisk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main home bg-grey&quot;]/div[2]/section[@class=&quot;section is-paddingless undefined&quot;]/div[@class=&quot;columns is-mobile is-multiline custom&quot;]/div[@class=&quot;column is-half&quot;]/div[@class=&quot;box grid effect-display&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-content&quot;]/div[@class=&quot;content min-height&quot;]/h4[@class=&quot;wrapword&quot;]</value>
   </webElementProperties>
</WebElementEntity>
