<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6b4f2868-75c1-46c7-9a54-d16ad3eb54d0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mobiledev.komuto.com/assets/produk/product-1513044142405-0.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>sandisk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main home bg-grey&quot;]/div[2]/section[@class=&quot;section is-paddingless undefined&quot;]/div[@class=&quot;columns is-mobile is-multiline custom&quot;]/div[@class=&quot;column is-half&quot;]/div[@class=&quot;box grid effect-display&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-left&quot;]/figure[@class=&quot;image img-product&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
