<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_icon-arrow-right</name>
   <tag></tag>
   <elementGuidId>50c47383-ef92-462e-9af6-0372b6b96699</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main main user bg-grey&quot;]/div[2]/div[1]/section[@class=&quot;section is-paddingless bg-white&quot;]/div[@class=&quot;profile-wrapp&quot;]/ul[1]/li[1]/span[@class=&quot;icon-arrow-right&quot;]</value>
   </webElementProperties>
</WebElementEntity>
