<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_content</name>
   <tag></tag>
   <elementGuidId>5034d80f-0268-46f1-83a9-8295ad9b122e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main main user bg-grey&quot;]/div[2]/div[1]/section[@class=&quot;section is-paddingless bg-white&quot;]/div[@class=&quot;profile-wrapp&quot;]/ul[1]/li[1]/div[@class=&quot;box is-paddingless&quot;]/article[@class=&quot;media&quot;]/div[@class=&quot;media-content&quot;]/div[@class=&quot;content&quot;]</value>
   </webElementProperties>
</WebElementEntity>
