<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>article_media</name>
   <tag></tag>
   <elementGuidId>8e7c01b3-7a7b-4476-abfd-f3b4345ac54f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>article</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main main detail edit-data bg-grey&quot;]/div[2]/section[@class=&quot;section is-paddingless has-shadow&quot;]/div[@class=&quot;seller-akun&quot;]/div[@class=&quot;profile-wrapp&quot;]/ul[1]/li[1]/div[@class=&quot;box is-paddingless&quot;]/article[@class=&quot;media&quot;]</value>
   </webElementProperties>
</WebElementEntity>
