<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Biodata</name>
   <tag></tag>
   <elementGuidId>10f0690c-b61c-4899-90de-c8488e7f7785</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Biodata</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main main detail edit-data bg-grey&quot;]/div[2]/section[@class=&quot;section is-paddingless has-shadow&quot;]/div[@class=&quot;seller-akun&quot;]/div[@class=&quot;profile-wrapp&quot;]/ul[1]/li[1]/div[@class=&quot;box is-paddingless&quot;]/article[@class=&quot;media&quot;]/div[@class=&quot;media-content&quot;]/div[@class=&quot;content&quot;]/p[1]/strong[1]</value>
   </webElementProperties>
</WebElementEntity>
